-- Los Autocmds (comandos automáticos) se cargan automáticamente en el evento VeryLazy
-- Autocmds por defecto que siempre se configuran: https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/config/autocmds.lua
--
-- Agrega cualquier autocmd adicional aquí
-- usando `vim.api.nvim_create_autocmd`
--
-- O elimina los autocmds existentes usando su nombre de grupo (que tiene el prefijo `lazyvim_` para los predeterminados)
-- por ejemplo: vim.api.nvim_del_augroup_by_name("lazyvim_wrap_spell")
